### ISSUE TITLE
missing dependencies

### ISSUE THREAD

**Issue by hanssl** [cchanxzy/React-Currency-Input-Field#1]
It would your package better if you would specify the dependencies.

<img width="914" alt="screen shot 2018-10-12 at 5 36 03 pm" src="https://user-images.githubusercontent.com/649957/46898280-69545580-ce45-11e8-8135-53d39e657f41.png">

**Comment by cchanxzy** [comment]
Hi,

Thanks for the suggestion.  However, I have React listed as a peer dependency so that it won't be installed twice and cause problems.

If a user is using this component then I would expect them to already have React installed, otherwise it would not work.

Hope that helps.
