### ISSUE TITLE
Indian Currency decimal support

### ISSUE THREAD

**Issue by dreamerchandra** [cchanxzy/react-currency-input-field#100]
Indian currency decimal support would be great

**Comment by cchanxzy** [comment]
Hi, just as an update, I have released [v3.0.0-beta.7](https://www.npmjs.com/package/react-currency-input-field/v/3.0.0-beta.7) which includes the option to pass an intl locale config. So, you should be able to use it like this:

```js
import CurrencyInput from 'react-currency-input-field';

<CurrencyInput intlConfig={{ locale: 'en-IN', currency: 'INR' }} />;
```

It's still in the testing phase, but I hope this helps :)
