### ISSUE TITLE
TextField Material UI design

### ISSUE THREAD

**Issue by dvirben123** [cchanxzy/react-currency-input-field#111]
Hi,
It could be nice to have a custom input, so this nice plugin can be as part of Material UI, for example, this plugin (https://www.npmjs.com/package/react-number-format) as a custom input so we can use TextField of material UI.
I can help with it if needed.
Dvir

**Comment by cchanxzy** [comment]
Hi, thanks for the suggestion!

I've never really used material UI, so this has not really come up before, but I can take a look into it.

**Comment by cchanxzy** [comment]
As an update on this issue:

I've added a way to pass a `customInput` for the component to render, but it doesn't seem to work with Material UI TextField.

I had a look at the [docs](https://material-ui.com/components/text-fields/#integration-with-3rd-party-input-libraries), and figured you can use it like:

```js
import React, { useState } from "react";
import CurrencyInput from "react-currency-input-field";
import TextField from "@material-ui/core/TextField";

const CurrencyInputCustom = ({ inputRef, onChange, ...props }) => {
  return (
    <CurrencyInput
      {...props}
      intlConfig={{
        locale: "de-DE",
        currency: "EUR"
      }}
      onValueChange={(value, name) =>
        onChange({
          target: { value, name }
        })
      }
    />
  );
};

export default function App() {
  const [value, setValue] = useState(123456);

  const handleOnValueChange = ({ target: { value } }) => {
    setValue(value);
  };

  return (
    <div className="App">
      <h1>React Currency Input Field</h1>
      <h2>Material UI Example</h2>
      <TextField
        onChange={handleOnValueChange}
        InputProps={{ inputComponent: CurrencyInputCustom }}
        value={value}
      />
    </div>
  );
}
```

[CodeSandbox](https://codesandbox.io/s/n4z5s)

Caveat: things get a bit weird if you specify the `ref`, so maybe avoid specifying a `ref` for now.

I hope this helps.

**Comment by dvirben123** [comment]
@cchanxzy Thank you! look nice, but I see that the steps not working right, the step down is working right,  but step up doesn't work at all. 
Also, there is any chance to add the up and down buttons as we have in a regular input number field?
