### ISSUE TITLE
safari focus of input

### ISSUE THREAD

**Issue by simonpkerr** [cchanxzy/react-currency-input-field#123]
just a little one...
when viewing the [demo page](https://cchanxzy.github.io/react-currency-input-field/)  in safari, one of the currency inputs focuses automatically. ideally this shouldn't happen.
We've noticed this in some implementations where we've used currency input.

<img width="1055" alt="Screenshot 2021-01-19 at 14 26 57" src="https://user-images.githubusercontent.com/995892/105047560-64d66880-5a62-11eb-9254-5d185bea0799.png">

**Comment by cchanxzy** [comment]
Hi, thanks for raising this bug, I think I have fixed it in v3.0.4.

Let me know if that's not the case, and I'll be happy to take another look :)

**Comment by simonpkerr** [comment]
thanks a lot, yes, that seems to have fixed it.  👍
