### ISSUE TITLE
Deletion does not work if there is a suffix with intlConfig configuration

### ISSUE THREAD

**Issue by PaTp0H** [cchanxzy/react-currency-input-field#129]
Hi, I ran into a terrible problem! I want to customize the input of numbers into the input using intlConfig lacquerization, but after entering the value, it is not deleted if there is a suffix, but especially if this type is US$, please tell me, do you plan to fix this problem in the near future? So I don't want to look for an alternative, your code is perfect for my implementation.

P.S. Thanks for making a cool feature!

**Comment by cchanxzy** [comment]
Hi, I'll try to help if I can but I'm not sure what you mean, could you give me an example of the code? or what value you're passing in?

**Comment by PaTp0H** [comment]
If I have, for example, the locale France and the currency selected is USD, then this is the output in the input, for example "343423423 $ US" (US dollars) after that I cannot remove the value from the input using Backspace

And for example, I would like to prohibit the withdrawal of Currency through a prefix / suffix in the input, just leave the format of the numbers depending on the locale, is it possible? I've tried passing prefix = {undefined} suffix = {undefined} to props but nothing happens ...

Please help, and thanks for the quick response!

**Comment by cchanxzy** [comment]
Do you mean [something like this](https://codesandbox.io/s/cool-wood-ium9n?file=/src/App.js)?

I _suspect_ the problem might be if you're using `Number(value)` then it might be erroring because it doesn't think it is a valid number, thus not setting the value?

**Comment by PaTp0H** [comment]
Yes, due to the specifics of my application, I have to use Number(value), and I also use react-hook-forms and pass the input component to the controller https://react-hook-form.com/api#Controller (for good reason)

For your example, everything works correctly ((

I changed all the types into a string, but the problem persists, but I still repeat the question, can you remove the currency as a required parameter, so that I can only get the number formatting depending on the locale and nothing more?

**Comment by cchanxzy** [comment]
An okay yeah, I think I get what you mean, that isn't currently possible, but I think it should be a quick add.

I'm busy atm, but I'll try and implement it in a few hours.

**Comment by PaTp0H** [comment]
Simply excellent! Thanks a lot! I will wait for the update :)

**Comment by cchanxzy** [comment]
Just released v3.2.2, which will allow you specify the locale without the currency in `intlConfig`, so it should still format the value without the currency symbol.

```js
<CurrencyInput
      intlConfig={{ locale: "fr-FR" }}
      value={value}
      onValueChange={handleOnValueChange}
/>
```

Hope that helps, or let me know if you're still having problems.

**Comment by PaTp0H** [comment]
Everything is exactly as I need it! Thank you very much for the quick feedback !!!

**Comment by cchanxzy** [comment]
Great to hear.

I'd also suggest replacing the decimal separator to `.` if you need to convert to `Number` (assuming you know what the decimal separator is)

```js
Number(value.replace(decimalSeparator, '.');
```

Or, it might make sense if the `onValueChange` function actually returned a `Number` rather than a `string`, so that's something I might implement in the future if this problem comes up for other users.
