### ISSUE TITLE
Entering negative values not working as expected

### ISSUE THREAD

**Issue by shivs077** [cchanxzy/react-currency-input-field#131]
Hi,
On mount of the CurrencyInput component, when I try to enter the a negative value, as soon as I enter '-', the cursor always resets to the start of the input, on further entering numbers, the '-' disappears from the start.
This issue occurs with and without prefix and only on the first mount when there is no defaultValue or value is empty/undefined. Once you clear the input field, it works as expected. Please refer to the video attached.

https://user-images.githubusercontent.com/31445561/106386829-de743c00-63fc-11eb-8676-08ae71e41d4d.mp4

Codesandbox link:
https://codesandbox.io/s/staging-bird-8syt2?file=/src/App.js

**Comment by cchanxzy** [comment]
Thanks for getting in touch!

Yes, that's a bug. The video and code sandbox was very helpful 👍

I've just merged a fix, so v3.2.3 should contain the fix. Hope that helps.

Feel free to re-open this issue if the problem persists :)
