### ISSUE TITLE
TypeError: n.toFixed is not a function

### ISSUE THREAD

**Issue by pbenschop** [cchanxzy/react-currency-input-field#134]
The above exception occurs when you use the up and down arrows.

**Comment by cchanxzy** [comment]
Hi, what is the value in the input before you step up/down? Even better if you could include a code snippet or code sandbox so I can try to replicate locally.

**Comment by cchanxzy** [comment]
Closing issue as I don't have enough information to re-produce.

Feel free to re-open if this comes up again.
