### ISSUE TITLE
Cursor jumps 2 places to the left when entering a decimal point

### ISSUE THREAD

**Issue by pbenschop** [cchanxzy/react-currency-input-field#135]
Select the current value and start entering a new value. When you enter a decimal point to (in order to enter the 2 decimals), the input cursor jumps 2 places to the left (which of course is unexpected and causes you to enter something different than what you had intended).

**Comment by cchanxzy** [comment]
Hi, could you include a code snippet or code sandbox of how you're implementing the component, because I can't replicate unless I know what props you're passing in. Thanks

**Comment by cchanxzy** [comment]
Closing issue as I don't have enough information to re-produce.

Feel free to re-open if this comes up again.
