### ISSUE TITLE
Prefix Returns NAN

### ISSUE THREAD

**Issue by Rickal-Hamailton** [cchanxzy/react-currency-input-field#136]
for some reason if I add prefix JMD I get a NAN value displayed it was working fine a few months ago.

**Comment by cchanxzy** [comment]
Sorry about that! There were some big changes in v3, so that might have broken something.

I've just merged a fix, v3.2.4 should include it.

I've added this scenario as a unit test, so hopefully it shouldn't break again. 

If you notice any more issue, please get in touch again :)
