### ISSUE TITLE
Widen peer dependency range to include React 17

### ISSUE THREAD

**Issue by georgesmith46** [cchanxzy/react-currency-input-field#140]
https://github.com/cchanxzy/react-currency-input-field/blob/59797a6c5ed29add59914db9f5992d68c2513918/package.json#L84

Could this be changed to `^16.9.0 || ^17.0.0`?

I've done some testing myself and haven't noticed any issues but it's probably best to review the [changes in React v17](https://reactjs.org/blog/2020/10/20/react-v17.html)

Thanks

**Comment by alexporthal** [comment]
I use React 17.0.1 and I also need this update.

**Comment by cchanxzy** [comment]
That's a good shout. Just merged a PR for this change.

I haven't used much of React v17 myself with the component, but reading the docs, I don't expect anything to break.

If you notice any issues, feel free to raise another issue here :)
