### ISSUE TITLE
unable to empty the input

### ISSUE THREAD

**Issue by nicokant** [cchanxzy/react-currency-input-field#143]
Hi, I'm having a problem while trying to empty the input using backspace.
After I get to the last number I'm unable to delete it or set to 0 easily.
For example I if the value is 20 and I want to delete it using backspace I get an undeletable 2, if now I want to set it to 0 I have to write 20 and then using the arrow keys move and delete the number 2.

I think that would improve greatly the UX if when I delete every number I get a 0 in the input

**Comment by cchanxzy** [comment]
Hi, that sound's like an issue with how you're handling `onValueChange`. Can you post a code snippet?

Because what you're saying is entirely possible, see this [CodeSandbox](https://codesandbox.io/s/kind-mestorf-73408?file=/src/App.js:583-596)

**Comment by cchanxzy** [comment]
Hi, I'm going to close this issue now, please feel free to re-open if you're still encountering problems.
