### ISSUE TITLE
Negative value is reset to positive with a currency prefix

### ISSUE THREAD

**Issue by bartvanremortele** [cchanxzy/react-currency-input-field#146]
When you enter a negative value with a currency that uses a prefix the negative value is lost as soon as you enter more than 1 digit. 

https://codesandbox.io/s/cocky-bhaskara-cxt75?file=/src/App.js

You can test it in this sandbox by typing -1200

**Comment by cchanxzy** [comment]
Woah that is very weird and bad! I'll have a look into this immediately.

**Comment by cchanxzy** [comment]
I've just merged a fix for this, please update your package to v3.3.1

Feel free to re-open if this issue if it is still happening.

Thanks for bringing this to my attention! I did not notice it myself as I normally specify `prefix` rather than use `intlConfig`
