### ISSUE TITLE
fixedDecimalLength on Load

### ISSUE THREAD

**Issue by carmo-evan** [cchanxzy/react-currency-input-field#150]
Hi! Thank you for the nice currency input component, very handy.

For my use case, fixedDecimalLength only being applied onBlur becomes a problem. All of my values come from the server in cents, and when in edit mode, I'd like to start off by displaying them in the correct format (divided by 100 with two decimals). However, they appear without the decimals until they're clicked and then blurred. Any work around this?

Thanks!

Evan

**Comment by cchanxzy** [comment]
Hi, I understand what you're saying, but I don't think that's something I'll likely build into this component, as it seems more reasonable to have the `value` already formatted and then passed in.

One workaround I can think of: you can take a look at [fixedDecimalValue.ts](https://github.com/cchanxzy/react-currency-input-field/blob/master/src/components/utils/fixedDecimalValue.ts) which is being used in the component. This is open source so feel free to copy the function and format your value before passing it in.
