### ISSUE TITLE
Voice Over Accessibility Issue

### ISSUE THREAD

**Issue by LeeroyJenks** [cchanxzy/react-currency-input-field#152]
Something weird happens while using voiceover and you type in numbers that go into the thousands. It looks like the voice over ignores the first number of the sequence.

![image](https://user-images.githubusercontent.com/3408364/113208166-7c3e8880-923f-11eb-8df2-b3a83b5f0924.png)

To recreate:
1. Set up a simple field or use one from the examples
2. Start a voice over session
3. Type a number longer than 3 digits

**Comment by cchanxzy** [comment]
Hi, thanks for raising this issue!

I have to admit, I have not done much voiceover testing for this component, but I will try and figure out what going on.
