### ISSUE TITLE
Unexpected cursor movement

### ISSUE THREAD

**Issue by scottpchow23** [cchanxzy/react-currency-input-field#153]
When playing with your component, I noticed some issues with the cursor's position

The below gif's typing sequences is `123456789{left}{left}{left}{delete}{delete}`

![Kapture 2021-03-31 at 17 22 37](https://user-images.githubusercontent.com/15284810/113226766-cfb3d500-9245-11eb-98af-5d3bede6228e.gif)

I would either expect the first `{delete}` to move the cursor over the `groupSeparator` or to delete the number preceding it. I certainly don't expect my cursor to jump all the way to the end of the input value.

Hope this helps!

**Comment by scottpchow23** [comment]
Here's an RTL test for this behavior:

```tsx
it('should handle backspace with decimal scale and group separators', () => {
    const { getByRole } = render(
      <CurrencyInput
        defaultValue=""
        onValueChange={onValueChangeSpy}
        groupSeparator={','}
        decimalScale={2}
        prefix="$"
      />
    );
    const textbox = getByRole('textbox');
    userEvent.type(textbox, '123456789');
    expect(textbox).toHaveValue('$123,456,789');
    userEvent.type(textbox, '{arrowleft}{arrowleft}{arrowleft}{delete}{delete}');
    expect(textbox).toHaveValue('$1,234,789');
  });
```

**Comment by scottpchow23** [comment]
I played around with it locally; it seems like the following update to `processChange` would fix the given example:

```tsx
if (selectionStart !== undefined && selectionStart !== null) {
	  // Prevent cursor jumping
	  let cursor = selectionStart;
	  if (formattedValue !== stateValue) {
	  	cursor = selectionStart + (formattedValue.length - value.length) || 1;
	  }
	  setCursor(cursor);
	  }
	  if (formattedValue !== stateValue) {
	  	setStateValue(formattedValue);
	  }
}
```

Basically, you need to trigger the `useEffect` to set the cursor position more often (in this case, we `setCursor` to something different).

**Comment by scottpchow23** [comment]
Unfortunately, it would still fail this test:

```tsx
  it('should handle backspace with decimal scale and group separators', () => {
    const { getByRole } = render(
      <CurrencyInput
        defaultValue=""
        onValueChange={onValueChangeSpy}
        groupSeparator={','}
        decimalScale={2}
        prefix="$"
      />
    );
    const textbox = getByRole('textbox');
    userEvent.type(textbox, '123456789');
    expect(textbox).toHaveValue('$123,456,789');
    userEvent.type(
      textbox,
      '{arrowleft}{arrowleft}{arrowleft}{delete}{delete}{arrowright}{delete}{delete}'
    );
    expect(textbox).toHaveValue('$1,234,789');
  });
```

**Comment by scottpchow23** [comment]
Also, the RTL tests do not seem to respect `inputRef.currentSetSelection` in these tests, so they _still_ fail (even if it doesn't reproduce manually).

**Comment by cchanxzy** [comment]
Hi, sorry only just seeing this issue now. 

Yes, test coverage for cursor movement has always been a bit of a blind spot, it's quite hard to test and verify with RTL because like you have observed, it doesn't always behave like it does in the browser. 

I've never noticed bug, so I really appreciate you raising this issue.

I will take a look, and see what's going...

**Comment by cchanxzy** [comment]
Hi, sorry for the delay. This should be fixed now. Please try v3.3.2

You were correct that the `useEffect` needed to be triggered more often. Hopefully my solution won't cause any unintended side effects 🤞 

Let me know otherwise!
