### ISSUE TITLE
DecimalScale property adds padding when there is no decimal

### ISSUE THREAD

**Issue by Sayf-Khan** [cchanxzy/react-currency-input-field#156]
Hello,

I was using this library and found that the Decimal Scale Property is padding any value I add into the currency input even if the user has not entered a decimal point.

![image](https://user-images.githubusercontent.com/45860056/115031103-b5256100-9ebf-11eb-9e95-b2c90d938377.png)

Code below:

          <CurrencyInput
            name={name}
            placeholder="Enter Value"
            decimalsLimit={2}
            decimalScale={2}
            onValueChange={(value: string | undefined) => {
              if (value === undefined) value = "0";
              setFieldValue(name, parseFloat(value));
            }}
          />
Note I am using formik here.

My understanding of this feature was that padding or trimming only occur when the user has added a decimal point which is why it is distinct from fixedDecimalLength property.

**Comment by cchanxzy** [comment]
Hi, I admit this is a bit of a confusing area, but there are subtle differences between `decimalLimit`, `decimalScale` and `fixedDecimalLength`

> `decimalsLimit` and `decimalScale` are similar, the difference is `decimalsLimit` prevents the user from typing more than the limit, and `decimalScale` will format the decimals onBlur to the specified length, padding or trimming as necessary.

> Example: If decimal scale 2: 1.5 becomes 1.50 and 1.234 becomes 1.23

https://www.npmjs.com/package/react-currency-input-field#decimal-scale-and-decimals-limit 

Whereas `fixedDecimalLength` will place the decimal in a value eg. '123' becomes '1.23' if `fixedDecimalLength` is 2.

So, if you don't want padding/trimming of decimals then don't pass in `decimalScale`
