### ISSUE TITLE
Why does this keep adding different numbers?

### ISSUE THREAD

**Issue by noobshow** [cchanxzy/react-currency-input-field#157]
For an example add a 9 to this 999999999999999 and it will be converted to 10,000,000,000,000,000, even adding very long numbers get changed, this isn't great for a web app dealing with money...

I can't see any docs revealing why this is happening or how to stop it, tried `decimalScale={undefined}`, nothig changed...

Please, help

**Comment by noobshow** [comment]
I think it has to deal with parseFloat having issues with big numbers

I'm not sure, but it might have to do with this line https://github.com/cchanxzy/react-currency-input-field/blob/242ec908d6eb34b1767b21b21515d5ea25e3c80e/src/components/CurrencyInput.tsx#L192 

The bug I'm experiencing seems to be complained about here too...

**Comment by noobshow** [comment]
https://stackoverflow.com/questions/4288821/how-to-deal-with-big-numbers-in-javascript

Check this out

**Comment by noobshow** [comment]
Figured this plugin once used Number() as seen here https://github.com/cchanxzy/react-currency-input-field/blob/5c42788be926e929b2da2f8ab89bf666a3dd2f4a/src/components/CurrencyInput.tsx#L183 what went wrong?

**Comment by noobshow** [comment]
Testing Number also have same bug... You can use any library capable of Big Numbers?

**Comment by noobshow** [comment]
This library uses parseFloat too but the test I ran on it seems OK, even with wide numbers https://www.npmjs.com/package/react-number-format
Is there something else going on under the hood?

**Comment by noobshow** [comment]
I tried pushing an update yesterday, but figured the library uses Intl.NumberFormat.formattoparts and I can't get that to work with Big Number string.

**Comment by cchanxzy** [comment]
Hi, thanks for getting in touch.

Yes, I am aware there are some issues when a large digit number is entered. It was never my intention to handle large numbers like `999999999999999` so I've never really looked into handling it to be honest.

In the future I _might_ implement a solution, but if you're in a rush I would recommend either:

- Forking the project and implementing your own solution
- Avoid large numbers
- Use a different library (https://www.npmjs.com/package/react-number-format is a good shout)

Sorry my reply isn't particularly helpful.

**Comment by noobshow** [comment]
Hi, glad to hear from you...
The issue has been affecting other parts of my dev since 2 days now(mostly my fault since i don't like proceeding with development when there's a pending bug to fix)

I had a fork pulled  and started implementing the solution using bignumber.js library for all number-based implementations..

I'm done with it though, been testing to be sure i didn't break anything...

> * Forking the project and implementing your own solution
> * Avoid large numbers
> * Use a different library (https://www.npmjs.com/package/react-number-format is a good shout)

Thanks for all suggestions, i'm unable to avoid large numbers since i'm in the finance sector.

After rigorous testing, i figured the [react-number-format](https://www.npmjs.com/package/react-number-format) i mentioned also faced the same issue and going deep into the code, i saw it uses parseFloat even in more lines than yours 😊

I appreciate your work on the library and it was as simple and advanced as i want, kinda have all features i wanted, if you want i can upload the fork to github too maybe it might help you solve a major problem for many people too facing same issue, just that you now have bignumber.js as a dependency

Good luck and thanks again
