### ISSUE TITLE
Value is not formatted on Windows 10 and Chrome Android

### ISSUE THREAD

**Issue by RodolfoCamposGlz** [cchanxzy/react-currency-input-field#158]
For some reason the formatted value like "$23,000" is just displaying correctly on mac os, i tried on my macbook safari, chrome, firefox and is working propertly, but for some reason on windows im just getting "23000" on the input

**Windows Google Chrome:**
![image](https://user-images.githubusercontent.com/56204868/115968803-2c31a980-a4ff-11eb-807e-783bd7845754.png)

**Mac os Google Chome**
![image](https://user-images.githubusercontent.com/56204868/115968883-8a5e8c80-a4ff-11eb-8566-00171402a45c.png)

**Comment by cchanxzy** [comment]
Hi, thanks for raising this issue.

I mainly work on Mac OS, so haven't noticed this bug personally. But, I will investigate on my windows machine soon.

**Comment by RodolfoCamposGlz** [comment]
> Hi, thanks for raising this issue.
> 
> I mainly work on Mac OS, so haven't noticed this bug personally. But, I will investigate on my windows machine soon.

i think is related with the Intl Config
![image](https://user-images.githubusercontent.com/56204868/117069875-a1b52b00-acf2-11eb-972a-31b1eb26991f.png)
it works when i test it on the example page with the us intl option
my current intl configuration on my pc is:
![image](https://user-images.githubusercontent.com/56204868/117070003-ce694280-acf2-11eb-8231-4c3ccafc7c80.png)
