### ISSUE TITLE
Component is not compatible with iOS 12

### ISSUE THREAD

**Issue by petergombos** [cchanxzy/react-currency-input-field#159]
Breaks because of `Intl.NumberFormat.prototype.formatToParts`

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/formatToParts

Is there a workaround?

**Comment by cchanxzy** [comment]
Hi, this has come up [previously](https://github.com/cchanxzy/react-currency-input-field/issues/142), and `Intl.NumberFormat.formatToParts` is a integral part of this component unfortunately, so there's much of a workaround.
