### ISSUE TITLE
Leading 0s at the end of the number if the number has more than 13 digits.

### ISSUE THREAD

**Issue by YeisonHunt** [cchanxzy/react-currency-input-field#172]
**Describe the bug**
After 13 digits, the formatter starts to fill with zeros at the end of the number. 

**To Reproduce**
1. Install version 3.4.1 but it seems it comes from before, use an example of the page and start typing a big number. (13+digits)

**Expected behavior**
Formatted number as normal.

**Comment by cchanxzy** [comment]
Hi, this is a known issue (#157), it is to do with javascript's `parseFloat` see https://stackoverflow.com/questions/7988827/parse-float-has-a-rounding-limit-how-can-i-fix-this

**Comment by vincaslt** [comment]
is there a way to fix this though? 
![image](https://user-images.githubusercontent.com/944727/163576081-e5b96a31-f9c1-4540-9286-af871eefbe26.png)
