### ISSUE TITLE
Setting value to `null` causes the input to show `NaN`

### ISSUE THREAD

**Issue by Smashman** [cchanxzy/react-currency-input-field#176]
This isn't necessarily a bug, so just thought I'd start the dialog.

When a regular input field is passed `null` it shows nothing at all, I feel like this is expected behaviour and am wondering if the current behaviour is intentional and if not, whether it should be changed.

Examples:
![image](https://user-images.githubusercontent.com/2972388/122034639-9fea8700-cdc9-11eb-8724-658e97be1fde.png)
![image](https://user-images.githubusercontent.com/2972388/122034683-aa0c8580-cdc9-11eb-9ba2-3fd286d2a450.png)

Thanks

**Comment by cchanxzy** [comment]
Hi, thanks for bringing this up. I don't _think_ this is a design decision (not that I can remember haha).

Yes I agree, `null` should not be returning `NaN`.

I'll try to fix.
