### ISSUE TITLE
Cursor is moved when entering only a decimal point

### ISSUE THREAD

**Issue by georgesmith46** [cchanxzy/react-currency-input-field#178]
**Describe the bug**
I've noticed a bug where if you enter only a decimal point into the field, the cursor is moved to the start. This appears to have been introduced in #155

**To Reproduce**
1. Go to Example 1 in the demo
2. Select the entire value in the input
3. Press `.`
4. The cursor is at the start of the input

**Expected behavior**
The cursor should be after the decimal point. If you wanted to enter `.99`, `99.` will be entered instead.

**Comment by cchanxzy** [comment]
Hi, firstly sorry for the late reply! I was taking a bit of break from this project to focus on other things.

I think what's happening is that, you're only selecting the value and not the entire string including the currency symbol, so you end up typing `£.`, which cannot be parsed so it is treated as an invalid value.

This feels a bit edge case and I'm not sure if it worth a fix tbh.

**Comment by karun012** [comment]
You could do a little hack by adding a keyUp handler
```Javascript
onKeyUp={(e) => {
                    const currentValue = e.currentTarget.value;
                    if (currentValue === '.') {
                        //Change value to 0. and move cursor to the end
                        e.currentTarget.value = '0.';
                        e.currentTarget.setSelectionRange(e.currentTarget.value.length, e.currentTarget.value.length);
                    }
                }}
```
