### ISSUE TITLE
Add support for currency sign

### ISSUE THREAD

**Issue by BaharDev** [cchanxzy/react-currency-input-field#179]
**Describe the bug**
Right now the intlConfig doesn't accept currency sign, in case we need to pass currencySign as 'accounting' so it shows negative sign as parentheses, would be great if the component can support that option.

**Comment by cchanxzy** [comment]
Hi, sorry I'm not sure what currency sign you mean?

**Comment by BaharDev** [comment]
Sorry for not being clear, setting currencySign to accounting on intlConfig will change the negative sign to (..), basically Im asking if there could be a support for that to show negative with parentheses.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/NumberFormat

**Comment by cchanxzy** [comment]
>  basically Im asking if there could be a support for that to show negative with parentheses

Oh right, so like if the value is `-5` then it will show `(5)`, I understand now.

Unfortunately, that is not supported at the moment, and would take a bit of work to add as a feature.

If there is enough interest from the community, I may consider trying to add it...
