### ISSUE TITLE
Export src

### ISSUE THREAD

**Issue by simonpkerr** [cchanxzy/react-currency-input-field#180]
hi, thanks for the awesome package btw. 
we're having some issues pulling in the package into our library using rollup and commonjs. I suspect its related to [this](https://github.com/rollup/plugins/issues/872) issue.
I was wondering if you could provide an export of the unbuilt code? then our library can just build it along with all the other components. Thanks

**Comment by cchanxzy** [comment]
Hopefully this should be resolved with PR #182 from @georgesmith46.

Let me know if otherwise!
