### ISSUE TITLE
ESM build output

### ISSUE THREAD

**Issue by georgesmith46** [cchanxzy/react-currency-input-field#181]
This is a request to add an ES modules build output so that consuming apps can properly tree shake this package. This is a fairly small package so the tree shaking benefits would be negligible however it should also fix bugs like #180 where build tools are confused by the multiple exports.

Unfortunately, Webpack [does not currently support an ESM output](https://github.com/webpack/webpack/issues/2933) so it would likely require migrating to another build tool like [rollup](https://github.com/rollup/rollup/wiki/pkg.module).

I'm happy to create a PR for this if it's something you would find useful.

**Comment by cchanxzy** [comment]
> Unfortunately, Webpack does not currently support an ESM output so it would likely require migrating to another build tool like rollup.

I don't mind moving to rollup as the build tool if it the better option. Could/should wepback still kept as a dev tool for running locally? 

> I'm happy to create a PR for this if it's something you would find useful.

Yes that would be great, my time to work on this project has been limited recently, so any help from the community would be appreciated.

**Comment by georgesmith46** [comment]
Thanks @cchanxzy

I've raised #182 for this so if you could take a look when you get a chance, that would be great.
