### ISSUE TITLE
When decimalsLimit is set to 0 and decimalSeparator to any value, it allows decimal input

### ISSUE THREAD

**Issue by nec-willian** [cchanxzy/react-currency-input-field#189]
**Describe the bug**
When the properties below are set
`decimalsLimit=0`
`decimalSeparator=","`
The input will allow 2 decimals

**To Reproduce**
1. Create any CurrencyInput
2. Set decimalsLimit to 0
3. Set decimalSeparator to ,
4. Type anything

**Expected behavior**
The **decimalLimit** should be considered even with **decimalSeparator** set

**Comment by cchanxzy** [comment]
Hi, I believe this is because the `decimalSeparator ` is the same as the default `groupSeparator`.

I would try `disableGroupSeparator={true}`.

Let me know if that helps.
