### ISSUE TITLE
Not showing decimals

### ISSUE THREAD

**Issue by RichardKentos** [cchanxzy/react-currency-input-field#194]
**Describe the bug**
I cannot see decimals even though this is set. 
```
allowDecimals={ true }
decimalScale={ 2 }
decimalSeparator=","
```

Also on your site https://cchanxzy.github.io/react-currency-input-field/, the first example in which the decimals should work, is not working as expected.

**To Reproduce**
1. Create currency input 
2. Set allowDecimals={true}
3. Try writing decimals in the 1. example  on https://cchanxzy.github.io/react-currency-input-field/

**Expected behavior**
I would like to have input in which I can write decimals.

**Comment by cchanxzy** [comment]
Hi, I believe this is because the `decimalSeparator ` is the same as the default `groupSeparator` (which will also likely be `,`). I've added a fix to throw an error if that happens so it is more explicit.

Let me know if that helps.
