### ISSUE TITLE
Field not getting clear when using undefined

### ISSUE THREAD

**Issue by diego-hourly** [cchanxzy/react-currency-input-field#196]
**Describe the bug**
Found a weird behaviour when resetting the value after the user has type something. When I programmatically assign a value as `undefined` it's not clearing the field just remains as it was but using empty string does clears the field. Not sure if is intentional.

**To Reproduce**
1. Go to https://codesandbox.io/s/testing-react-currency-input-field-undefined-as-value-cnmqw
2. Type a number on any on the fields
3. Click the reset button 
or click on default button and then the reset button

**Expected behavior**
The input field gets clear when I programmatically assign a value

**Code Sandbox**

 https://codesandbox.io/s/testing-react-currency-input-field-undefined-as-value-cnmqw

**Additional context**

**Comment by cchanxzy** [comment]
Hi,

Yes this is intentional because the component  can be used without a value (uncontrolled), so value would be `undefined` in that case, and we wouldn't want the value to be cleared in that case.
