### ISSUE TITLE
If currency in intl config changes on uncontrolled input, format doesn't change

### ISSUE THREAD

**Issue by osdiab** [cchanxzy/react-currency-input-field#201]
**Describe the bug**
I expect the currency format to change if the locale config changes, even if the input is not controlled; however that doesn't seem to happen.

**To Reproduce**
1. make a currency input that is not controlled
2. assign its intl config dynamically
3. update the intl config

it won't change format until you change the value

**Expected behavior**
see above.

**Code Sandbox**
https://codesandbox.io/s/great-flower-11ucj?file=/src/App.js

**Additional context**
Working around by controlling the component value.

**Comment by osdiab** [comment]
Bump

**Comment by osdiab** [comment]
still an issue

**Comment by osdiab** [comment]
ping

**Comment by osdiab** [comment]
Bump

Omar

**Comment by osdiab** [comment]
Still a problem

Omar

**Comment by osdiab** [comment]
this is still a problem :P

**Comment by leonardomso** [comment]
Can confirm that this is still happening. Any workarounds?
