### ISSUE TITLE
Max length and decimal scale conflict

### ISSUE THREAD

**Issue by simonpkerr** [cchanxzy/react-currency-input-field#205]
**Describe the bug**
If maxLength and  decimalScale are both set, this can result in not being able to remove characters from the input.

**To Reproduce**
1. set maxLength to 5
2. set decimalScale to 2
3. Type 5 characters into the input
4. On blur, 3 additional characters will be added (.00)
5. Go back into the input
6. Can't delete numbers from the end of the input. You can only delete the entire number and start again

**Expected behavior**
Should be able to delete characters from the end of the input.

**Code Sandbox**
https://codesandbox.io/s/epic-ramanujan-0qn63?file=/src/App.js

**Additional context**

**Comment by simonpkerr** [comment]
bump

**Comment by Thorvarium** [comment]
bump

**Comment by martingg88** [comment]
any idea how to solve this issue?
