### ISSUE TITLE
Decimal not accepted when user types with no previous decimal

### ISSUE THREAD

**Issue by astromikejr** [cchanxzy/react-currency-input-field#206]
I'm attempting to use this for a tool I'm creating and I've found some strange behavior.  When the user highlights the entire contents of the CurrencyInput box, and then starts to type 1500.25 (localization with '.' as decimal separator), the decimal never shows up and the value appears as $150,025.  The user can go back and add the '.' back in after the fact, but is unable to with the initial typing.

I've set the following settings:
```
<CurrencyInput decimalScale={2}
               allowDecimals={true}
               value={amount}
               onValueChange={this.updateAmount}
               intlConfig={{ locale: 'en-US', currency: 'USD' }}
               className="Money"/>
```

I think I have found where this can be resolved, but I don't have an environment set up for the ESLint setup you are using.  I'm still new to React (but not new to software in the least bit).  I believe this may be resolved by adding an additional check inside the if at line 128 in CurrencyInput.tsx (CurrencyInput::processChange).  If I can get an environment set up to give this a shot, I'll create a branch and submit a pull request.
```
      /* istanbul ignore next */
      if (selectionStart !== undefined && selectionStart !== null) {
        // NEW CHECK
        if (value.charAt(value.length - 1) === decimalSeparator) {
          formattedValue += decimalSeparator;
        }
        // END NEW CHECK
        // Prevent cursor jumping
        const newCursor = selectionStart + (formattedValue.length - value.length) || 1;
        setCursor(newCursor);
      }
```

**Comment by osrl** [comment]
I have the same issue. User can copy paste a decimal point number, or can move cursor back and add decimal separator. But can't write decimal number sequentially

**Comment by osrl** [comment]
Can't write negative values either
