### ISSUE TITLE
Missing Source maps lead to warning with webpack 5,  source-map-loader and no CRA configuration

### ISSUE THREAD

**Issue by adriankast** [cchanxzy/react-currency-input-field#210]
**Describe the bug**
Using react-currency-input-field in a project with webpack5 and a custom webpack configuration (including source-map-loader) leads to warnings starting with every version newer than v3.4.1 of react-currency-input field. The warnings differ. Bug repo uses v3.6.0

**To Reproduce**
1. Clone bug-report-repo below
2. Run `npm install`
3. Run `npm start` or `npm run build`
4. See error messages

**Expected behavior**
No warning/error message, source maps are found.

**Code Sandbox**
[Example Repo to replicate the bug](https://github.com/adriankast/demo-rcfi-bug-1)

**Comment by adamsoutar** [comment]
Since the source maps use paths like `../src/components/CurrencyInput.tsx` (see `dist/index.esm.js.map`)

I wonder if a fix for this would be to change the `package.json` `files` section like so:

```json
"files": [
    "dist/**/*",
    "src/**/*"
  ],
```

That way shipping the source code as well as just the `dist` packaged versions, so Webpack can find and match up the source maps/original code.

**Comment by mpsijm** [comment]
Alternatively, setting `sourcemap: "inline"` at https://github.com/cchanxzy/react-currency-input-field/blob/master/rollup.config.js#L16 might help :slightly_smiling_face:

**Comment by adamsoutar** [comment]
Hey @mpsijm , 

That was a good shout. I tested out `sourcemap: "inline"`, unfortunately what that does is inline the sourcemap file in the compiled code, **not** inline the original source in the compiled code.

<img width="680" alt="image" src="https://user-images.githubusercontent.com/26578100/147247743-4fefe816-76d3-4181-87c9-67b40a62664a.png">

<img width="771" alt="image" src="https://user-images.githubusercontent.com/26578100/147247761-66ff4440-afc9-49d8-8596-93b1a8e92eef.png">

I've done a PR (#216) which fixes the issue and produces a package that Webpack doesn't complain about :)
