### ISSUE TITLE
Weired suffix behaviour

### ISSUE THREAD

**Issue by o-faro** [cchanxzy/react-currency-input-field#213]
My customer wants to add a label as suffix to input (large enterprise project, so no code example). 
I know the `suffix` prop is not actually made for this and I use it together with `intl` prop. The outcome on the first glance is quite good. 
![image](https://user-images.githubusercontent.com/9883445/145370094-62277c53-00a9-4be3-8774-830944feb7d7.png)
Writing `30` ends up in 
![image](https://user-images.githubusercontent.com/9883445/145370332-5d827ee6-3c8f-4f1f-b6cc-07043bdce860.png)
So groups get added, and the intl configuration is not overwritten like the documentation states. 
```         
<CurrencyInput
                id={label.replace(" ", "").toLowerCase()}
                name={label.replace(" ", "").toLowerCase()}
                placeholder={label}
                intlConfig={{ locale, currency }}
                {...{ type }}
                onValueChange={handleChange}
                key={`input-${label}`}
                className={handles.financeCalculatorInput}
                suffix={" " + label}
            />
```
I am not doing a change request here, because this scenario is quite rare. Just pointing out weired behaviour here.

**Comment by ColinBohn** [comment]
Just saw this same behavior, seems to be an issue with having the character "m" included in the suffix.

**Comment by abakuz** [comment]
In my case, it happens with KG unit. Is there any update to fix this?

![image](https://user-images.githubusercontent.com/99644738/153830821-b9f50c5c-c37c-4353-80ac-d3f4f999e302.png)

**Comment by muh-hizbe** [comment]
> Just saw this same behavior, seems to be an issue with having the character "m" included in the suffix as by default this is assumed to be an abbreviation for "million". Passing the`disableAbbreviations` prop will fix the issue.

nice, this way was fixed my problem with suffix.
Thank's @ColinBohn
