### ISSUE TITLE
FixedDecimalLength prop + onBlur changes intended input value

### ISSUE THREAD

**Issue by ncharris93** [cchanxzy/react-currency-input-field#217]
**Describe the bug**
If the prop `fixedDecimalLength` is set,  when `onBlur` is triggered, numbers such as `200` will change to `2.00`

`123` » `1.23`
`350` » `3.50`
etc

**To Reproduce**
1. Go to forked sandbox
2. remove the default value
3. Enter `200`
4. click in the whitespace to trigger `onBlur`

**Expected behavior**
The input value of `200` would change to `200.00`

**Code Sandbox**

[Forked Sandbox](https://codesandbox.io/s/reverent-bash-dvwur?file=/src/App.js)

**Additional context**
I see that there are tests to actually show this is intended behavior (?!) 

So I guess I should just fork this repo, or will this request be addressed?

**Comment by ncharris93** [comment]
bump

**Comment by makis-spy** [comment]
Bump?

**Comment by chriskaya** [comment]
For people like me having the same issue (123 becomes 1.23) and arriving here:
Instead of using `fixedDecimalLength`, you just need to use [`decimalScale`](https://github.com/cchanxzy/react-currency-input-field#decimal-scale-and-decimals-limit)
