### ISSUE TITLE
Pass an empty string to "prefix" to override Intl Locale config and not display currency code

### ISSUE THREAD

**Issue by jvzaniolo** [cchanxzy/react-currency-input-field#222]
**Describe the feature**
I would like to pass an empty string to "prefix" to override Intl Locale config and not display currency code

**To Reproduce**
```js
<ReactCurrencyInputField
    prefix=""
    intlConfig={{ locale: 'en-US', currency: 'USD' }}
/>
```

**Expected behavior**
When typing "1234.56" input field could format to "1,234.56" instead of "$1,234.56"

**Comment by felixfbecker** [comment]
Having the same issue, the problem is that the code uses `||` to default to the intl config and not `??`:

https://github.com/cchanxzy/react-currency-input-field/blob/ab788f5d70b1977870cf3cfd6c65619c8aa23cdd/src/components/CurrencyInput.tsx#L91

**Comment by Betree** [comment]
Would love to have that too, the workaround I'm using for now is to use a zero-width space (`​`, U+200B, &#8203).
