### ISSUE TITLE
Getting the error ReferenceError: Can't find variable: Intl

### ISSUE THREAD

**Issue by Garlicvideos** [cchanxzy/react-currency-input-field#224]
**Describe the bug**
Getting a render error from this module.

![image](https://user-images.githubusercontent.com/33229805/151179233-204a0ab2-31cf-4ebd-938a-a65653b65d13.png)

**To Reproduce**
1. Install the latest version of this package
2. 

    import CurrencyInput from 'react-currency-input-field';

    <CurrencyInput
        id="input-example"
        name="input-name"
        placeholder="Please enter a number"
        defaultValue={1000}
        decimalsLimit={2}
        onValueChange={(value, name) => console.log(value, name)}
    />;
3. `react-native run-android`

**Expected behavior**
A interface similar to the example given to appear

**Comment by osdiab** [comment]
Looks like you need to polyfill `Intl` on Android React Native. https://stackoverflow.com/questions/41736735/react-native-and-intl-polyfill-required-on-android-device
