### ISSUE TITLE
Cannot input negative or decimal point numbers

### ISSUE THREAD

**Issue by osrl** [cchanxzy/react-currency-input-field#232]
**Describe the bug**
User can copy paste a negative or decimal point number, or can move cursor back and add decimal separator. But can't write them sequentially. 

**To Reproduce**
1. Focus on empty input.
2. Hit -
3. No imput

1. Focus on empty input.
2. Hit 11.1
3. Writes 111 (didn't accept decimal sepertor)

I'm using `values.float` instead of value (because I need a float value, not string)
```tsx
const [value, setValue] = useState<number | undefined>();

<CurrencyInput
  value={value || 0}
  onValueChange={(value, name, values) => {
    setValue(values?.float || 0)
  }}
/>
```

**Additional context**
I think #206 is the same issue.

**Comment by SamuelNoB** [comment]
Hi I was getting a similar issue with the Input. Whenever the user try to type a decimal number, the decimal separator wasn't been typed.  
Ex
with `decimalSeparator=","`
1. with the empty input, if user type 12,4
2. the input value is 124

Did you find any solution?

**Comment by osrl** [comment]
No I didn't

**Comment by osrl** [comment]
removing the line `value={value || 0}` works as intende in this case @SamuelNoB . Though it may not be your case

**Comment by LawJolla** [comment]
This isn't the most elegant solution, but it works for me

```
    onValueChange={(value, maskedValue, values) => {
                if (value?.endsWith(".")) {
                  onChange(values.float.toFixed(1))
                } else {
                  onChange(values.float || 0)
                }
              }}
```

**Comment by prmkishor** [comment]
This video can helpful https://www.youtube.com/watch?v=dTRb6N9gJIQ
