### ISSUE TITLE
Cursor jumping issue if the ref passed isn't a ref object

### ISSUE THREAD

**Issue by osdiab** [cchanxzy/react-currency-input-field#247]
**Describe the bug**
If the ref you pass to a currency amount input isn't a mutable ref object but instead is a function, then the logic to prevent cursor jumping doesn't get triggered, and therefore the cursor jumps. This is particularly annoying since I want to pass several refs merged together into a single ref function into the currency input, but that causes it to jump around.

https://github.com/cchanxzy/react-currency-input-field/blob/d7c63d5f5398f30d37f3480129c8775a28d03f2e/src/components/CurrencyInput.tsx#L303-L314

**To Reproduce**
1. Pass a ref function to the currency amount input
2. try typing near a thousands separator comma
3. see that it jumps the cursor to the end

**Expected behavior**
both object and function refs work

**Code Sandbox**
https://codesandbox.io/s/dazzling-elion-jgo678?file=/src/App.js

**Additional context**
can work around by calling the ref function in a `useEffect()`.

https://www.loom.com/share/7d3feb2064054fa39608c21ec201b834

**Comment by osdiab** [comment]
still an issue

Omar

**Comment by s10mcow** [comment]
+1 same issue when using with react-hook-form

**Comment by FloorianB** [comment]
+1 same issue here using react hook form. Ref create cursor jump and bad behavior.

**Comment by s10mcow** [comment]
@FloorianB whats the setCleanRef trick? Am i missing it in the above code?
