### ISSUE TITLE
Suffix with number breaks value

### ISSUE THREAD

**Issue by makis-spy** [cchanxzy/react-currency-input-field#248]
**Describe the bug**

Adding a number to suffix "/1x" or /x1 or "1"

**To Reproduce**
suffix {"/1x"}

**Expected behavior**

**Code Sandbox**
If applicable, please fork this [CodeSandbox template](https://codesandbox.io/s/great-flower-11ucj?file=/src/App.js) and customise it to replicate your issue.

**Additional context**

**Comment by paul-orchid** [comment]
This is definitely still an issue. In my case the suffix is 'm3' and inputting a second number gets prefixed by a '3' from the suffix and the cursor is also in the incorrect place. Sandbox here: https://codesandbox.io/s/elated-bardeen-l0q8ke?file=/src/App.js
