### ISSUE TITLE
Swedish Krona error

### ISSUE THREAD

**Issue by Thorvarium** [cchanxzy/react-currency-input-field#255]
**Describe the bug**
When using the configuration below and typing more than 2 numbers the textbox changes to "NaN kr":
` <ReactCurrencyInput
      intlConfig={{ locale: "sv-SE", currency: "SEK"}}
  />`

**To Reproduce**
just insert the component with the given intlConfiguration and type 2 numbers.

**Expected behavior**
I expected the numbers to be formatted correctly on the Swedish Krona currency and locale

**Code Sandbox**
https://codesandbox.io/s/new-thunder-xk481x

**Comment by RasmusBuchholdt** [comment]
I have the same issue with Danish Kroner. It has to do with the abbreviations, where both SEK and DKK contains **K**, which means it will multiple whatever you enter with 1000 and that can result in `NaN`.

A temporary fix for you would be disabling abbreviations by passing `disableAbbreviations` like they explain [here](https://github.com/cchanxzy/react-currency-input-field#abbreviations).
