### ISSUE TITLE
Start typing from decimal

### ISSUE THREAD

**Issue by akagamina** [cchanxzy/react-currency-input-field#263]
Hi, 

Thanks for the awesome package.

I need to start typing from decimal.

if I type 22, it should be converted to 0.22.
if I type 122, it should be converted to 1.22 (with a 2-decimal limit).

is there any feature for this?

This is my input;

` <CurrencyInput
          placeholder={placeholder}
          id={name}
          value={value}
          name={name}
          onValueChange={onChange}
          prefix={'£'}
          step={1}
          maxLength={max}
          disabled={disabled}
          allowDecimals
          decimalsLimit={2}
          fixedDecimalLength={2}
          {...other}
        />`

**Comment by victorcarvalhosp** [comment]
I want to achieve the same behavior with this lib. Were you able to achieve it?

**Comment by artemis-prime** [comment]
Please turn of your stale bot feature!  These issues are not getting addressed and not coming up in searches!
