### ISSUE TITLE
Hello I am unable to provide customInput MUI TextField

### ISSUE THREAD

**Issue by WingsDevelopment** [cchanxzy/react-currency-input-field#265]
I am trying to render customInput, What I have so far is: 

```
type IProps = {
  name: string;
  rules?: RegisterOptions;
  defaultValue?: string;
};

type Props = IProps & TextFieldProps;

export default function RHFCurrencyField({ name, rules, defaultValue, ...other }: Props) {
  const { control } = useFormContext();

  return (
    <Controller
      name={name}
      rules={rules}
      control={control}
      render={({ field, fieldState: { error } }) => (
        <CurrencyInput
          name={name}
          groupSeparator=" "
          defaultValue={defaultValue}
          decimalsLimit={2}
          onValueChange={(value, name) => {
            field.onChange(value);
          }}
          customInput={() => <CurrencyTextField {...other} {...field } />}
        />
      )}
    />
  );
}

export const CurrencyTextField = React.forwardRef((props: Props, ref: any) => {
  return <TextField {...props} ref={ref} />;
});

```

And I am getting a warning, and input i 
react-dom.development.js:67 Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?
Check the render method of `CurrencyInput`.

**Comment by italosantana** [comment]
can you solve this? I have the same problem.

**Comment by lokucrazy** [comment]
@WingsDevelopment @italosantana Howdy, I was having a similar issue with the same fix you had:
`const CustomInput = React.forwardRef((props, ref: React.Ref<HTMLInputElement>) => <EuiFieldText {...props} inputRef={ref} />)`

but I just passed it into `customInput` I didn't wrap it around another function and that warning goes away
