### ISSUE TITLE
Cannot backspace when input digit hit maxLength

### ISSUE THREAD

**Issue by alanvsalan95** [cchanxzy/react-currency-input-field#274]
![image](https://user-images.githubusercontent.com/33516930/212310419-ef97a46b-2fc7-46f1-82c4-443975fcfba3.png)
![image](https://user-images.githubusercontent.com/33516930/212312158-68b54940-fbd8-4b8f-a731-148c725fa640.png)

Another issue, can introduce integer length which excluded the decimal places length? 
For eg if the input limit to (8,2), user can input max 8 integers and 2 decimal places (maxLength=8)
12,345,678.00 rather than 12,345.0 (comma and dot counted)

**Comment by martingg88** [comment]
does this issue can be solved?
