### ISSUE TITLE
Display wrong when type 0.999999999999999999

### ISSUE THREAD

**Issue by MauricioHernanCabrera** [cchanxzy/react-currency-input-field#285]
**Describe the bug**
When I try to add 0.999999999999999999 the component add a 1 in the integer part and if enter and leave of the component when I have this case the component add a 1 also

**To Reproduce**
- case 1
1. go to 0 to 0.999999999999999999
- case 2
1. put 0.999999999999999999
2. leave of the input
3. click on the input

**Expected behavior**
Avoid the auto add of 1

**Code Sandbox**
[example](https://playcode.io/1300374)

**Comment by atanasbozhkov** [comment]
I'm having the same issue - it will auto round up by 1 when decimals are high. 
This is reproducible on the Example page - on the component at the very bottom [https://cchanxzy.github.io/react-currency-input-field/](https://cchanxzy.github.io/react-currency-input-field/) 
![Recording 2023-05-16 095647](https://github.com/cchanxzy/react-currency-input-field/assets/1144752/2bdc7856-43a0-4be9-860b-0effaf438fab)
Here's a demo: 
![Recording 2023-05-16 095647](https://github.com/cchanxzy/react-currency-input-field/assets/1144752/2bdc7856-43a0-4be9-860b-0effaf438fab)

**Comment by mazmassa** [comment]
Hey Folks,

it still persists! Is that the case!?

https://github.com/cchanxzy/react-currency-input-field/assets/126461030/d67163da-2dcc-467e-b2d9-670c2351b35e

**Comment by atanasbozhkov** [comment]
Yep still persists for me as well - as well as easily reproducible on the demo page.

**Comment by Julio-de-Leon** [comment]
still an issue
