### ISSUE TITLE
onValueChange is triggered when input unfocused/blurred  

### ISSUE THREAD

**Issue by obouchari** [cchanxzy/react-currency-input-field#289]
**Describe the bug**
onValueChange handler is called every time input loses focus.

**To Reproduce**
N/A

**Expected behavior**
onValueChange should only trigger when the value has changed.

**Code Sandbox**
N/A

**Additional context**
N/A

**Comment by AM-Torabi** [comment]
I have the same issue, is there anyway to change this behavior?

**Comment by leonardomso** [comment]
It's probably the not best way to handle this but I solved this by setting again the value using the `onBlur` method, like this:

```
onBlur={(e) => {
  setFieldValue(inputName, value)
}}
```

**Comment by yaakovbeiss** [comment]
I am also experiencing this
