### ISSUE TITLE
Differences between 4 and 5 digits values

### ISSUE THREAD

**Issue by MarcosParengo** [cchanxzy/react-currency-input-field#291]
When value has 4 digits, the group separator is not present, but when the value has 5 digits, it is present

When the value has 4 digits:
```
<CurrencyInput
    decimalSeparator="."
    groupSeparator=","
    value={1000}
/>
```
This display the value as 1000 (instead of 1,000)

When the value has 5 digits:
```
<CurrencyInput
    decimalSeparator="."
    groupSeparator=","
    value={10000}
/>
```
This display the value as 10,000

**Comment by MarcosParengo** [comment]
Using intlConfig:{ locale: 'en-US' } the value is formatted correctly, but with the formatValue() function if it have not significant decimal value, the decimal aren't shown (that could be solved using fixedDecimals, but tha function ignores that param)

**Comment by LemanLemur** [comment]
I had the same issue and set `intlConfig` to `intlConfig:{ locale: 'en-US' }` works for me

**Comment by MarcosParengo** [comment]
that removes the trailing zeros :(

**Comment by LetMeDream** [comment]
@LemanLemur 
> I had the same issue and set `intlConfig` to `intlConfig:{ locale: 'en-US' }` works for me

Could you please explain how did you do that?

Did you use another library like react-intl or is it just a property on the 'CurrencyInput' that needs to be set?
