### ISSUE TITLE
fixedDecimalValue errantly changing number

### ISSUE THREAD

**Issue by atfergs** [cchanxzy/react-currency-input-field#292]
**Describe the bug**
The fixedDecimalValue function is returning the wrong parts of the split. With a fixedDecimalLength of 2, when supplied with the value "1111.11," the match value is [1111,11,11], and the function is returning match[1].match[2], changing the value to 11.11.

**To Reproduce**
1. Add a CurrencyInput control
2. Set the fixedDecimalLength to 2
3. Enter 1111.11 in the input
4. Tab out for blur
5. See new value of 11.11

**Expected behavior**
The value should remain 1111.11.

**Code Sandbox**
https://codesandbox.io/s/young-water-kq2kqr

**Additional context**

**Comment by viveleroi** [comment]
This is affecting us too. It only happens when `fixedDecimalLength` is set. I enter `2222.33` and it updates to `22.22`.

**Comment by cchanxzy** [comment]
This issue should be fixed in v3.6.12, but feel free to reopen issue if not. Thanks!
