### ISSUE TITLE
Can you style the input?

### ISSUE THREAD

**Issue by jcubic** [cchanxzy/react-currency-input-field#297]
I need to have custom-look currency input, that doesn't look like the browser's default input. Is there a way to style this thing? I don't see this in the documentation.

I would ask on discussion but they are disabled.

**Comment by scarabcoder** [comment]
Looks like it inherits most of the props of a regular <input> tag, just use the "className" prop to style it. It doesn't ship with any classes out of the box so you have complete control over how you want it to look,

**Comment by jcubic** [comment]
@omarmedex I don't use this library.

**Comment by dbaileydev** [comment]
@omarmedex I was able to style the input by just passing a `className` prop to the input.

**Comment by cchanxzy** [comment]
This component does not come styled, style it as you would a normal `<input ... />` field.
