### ISSUE TITLE
It is not accepting disabled prop

### ISSUE THREAD

**Issue by srika** [cchanxzy/react-currency-input-field#30]
`<CurrencyInput
                          value={1000}
                          name="input"
                          className=" curr-text-box"
                          allowDecimals={false}
                          onChange={this.updateInputField}
                          disabled={true}
                        />`

**Comment by cchanxzy** [comment]
Hi,

Thanks for raising this issue.

I've added `disabled` to the props now, so it should work if you update to v0.7.0.

Let me know if you have any other issues :)

**Comment by srika** [comment]
Thank you chun
