### ISSUE TITLE
How To Allow Negative Input on Mobile

### ISSUE THREAD

**Issue by ogheneovo12** [cchanxzy/react-currency-input-field#303]
When used on mobile, the keyboard doesn't bring up the option of using a negative symbol, after going through, i couldn't find if there were any specifics approach/solutions for such scenario
![WhatsApp Image 2023-07-31 at 13 41 09](https://github.com/cchanxzy/react-currency-input-field/assets/49083654/cc22779c-8405-46bd-9ecc-5b75d545c7e8)
![WhatsApp Image 2023-07-31 at 13 42 06](https://github.com/cchanxzy/react-currency-input-field/assets/49083654/65380be2-5753-47f3-9c19-6a6aaab0b636)

**Comment by ericblade** [comment]
it shouldn't be using the phone number input, you need negative numbers.   or use a different keyboard that does.   also, you can probably paste a - into it... just popping out possible workarounds, i don't know if any actually work with this.
