### ISSUE TITLE
[BUG] group separator cannot be empty when decimal is set to ","

### ISSUE THREAD

**Issue by yehhork** [cchanxzy/react-currency-input-field#304]
Greetings!
Thank you for such a great library! It is joy to use it.

[DESCRIPTION]
Unfortunately we have faced a bug related to separators - lib throws exception `decimal separator cannot be the same as groupseparator` when I try to use it with decimalSeparator="," and groupSeparator="" (empty string)

**Expected behavior**
Would be to have raw number with decimal separated with just comma and no groupSeparator

**Code Sandbox**
Here is codesandbox with repro, seems like bug was released in version newer than 3.3.2 [CodeSandbox template](https://codesandbox.io/s/frosty-wildflower-nfdc9d?file=/src/App.js)

Looking forward for feedback!
Thanks in advance.

**Comment by i-am-nikola** [comment]
Same issue!
