### ISSUE TITLE
Automatic decimal separtator replacing

### ISSUE THREAD

**Issue by vimtor** [cchanxzy/react-currency-input-field#308]
Users have a locale that automatically sets the appropriate decimal separator (`,` or `.`). However, some users don't follow their own locale rules. It would be nice to have a way so that `,` gets automatically replaced by `.` or vice versa.

**Comment by VladyslavL** [comment]
I wanted to create a relative issue, as this is a huge problem! 

Depending on the locale set on an iPhone's settings, a keyboard could include ',' or '.', but not both! 
So, there is possibly a case when the user won't be able to add decimals at all. 

@cchanxzy please try to fix it ASAP

![image](https://github.com/cchanxzy/react-currency-input-field/assets/5477308/71a32ce1-855a-4340-8662-41ca6dba824d)
