### ISSUE TITLE
Using it in Astro fails during build

### ISSUE THREAD

**Issue by maks-akymenko** [cchanxzy/react-currency-input-field#317]
Hey! Great library indeed, but I found one issue. Particularly, I'm using it in my custom react component and just importing it in there. It works fine during development, but when I'm trying to build it during deployment, it fails with the following error: 

`Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.`

I did a bit of investigation and seems like the issue is related to the way how you import types. E.g. 
<img width="849" alt="image" src="https://github.com/cchanxzy/react-currency-input-field/assets/31901974/eee6de0d-942f-4764-a813-91df262b75ba">

While when you import it as a type, it works correctly: 

<img width="849" alt="image" src="https://github.com/cchanxzy/react-currency-input-field/assets/31901974/39f7f357-a474-4347-8613-aba4471f7383">

There are a bunch of imports like that, and I think that might be an issue that causes my Astro build to fail. Because when I copy the component locally and replace all these type imports, it works correctly and doesn't fail during build.

**Comment by kengru** [comment]
It also happens to me, but on even on local using Remix with the Netlify runtime.

**Comment by yuleicul** [comment]
`client:only="react"` fixed for me
