### ISSUE TITLE
Unable to enter -.123 (negative number starting with decimal separator)

### ISSUE THREAD

**Issue by toneb** [cchanxzy/react-currency-input-field#336]
**Describe the bug**
Entering "-." gets immediatelly changed into "." only.

**To Reproduce**
1. Go to [Example 1](https://cchanxzy.github.io/react-currency-input-field/)
2. Enter minus sign, then decimal separator ("-.")
3. Value is changed to decimal separator only

**Expected behavior**
To be able to enter decimal values starting with "-."

**Code Sandbox**
n/a

**Additional context**
n/a

**Comment by sodiq2000** [comment]
@cchanxzy I have resolved this and made a PR
