### ISSUE TITLE
HTML 5 Validation

### ISSUE THREAD

**Issue by Sethlans** [cchanxzy/react-currency-input-field#34]
Hi, I've put the currency field inside a Form, when i try to submit it it fires the HTML 5 Validation, the pattern of the field accpet only number but with the currency prefix it says that I'm not respecting the correct format

**Comment by nuclearspike** [comment]
I have the same issue. The pattern that is created that the browser is checking does not contain the prefix so it's not valid.

**Comment by cchanxzy** [comment]
Hi, thanks for bringing this up!

I've removed the `pattern` type from the field because that was causing the problem. If you update to v0.8.2 then it should be fixed.

Feel free to reopen this issue if you're still having problems :)

**Comment by nuclearspike** [comment]
Thanks for getting this fixed so quickly! The workaround was to just shut off the prefix but it'll be better with it back in there. Thanks again!
