### ISSUE TITLE
fixedDecimalLength possibly not working as intended

### ISSUE THREAD

**Issue by daliborkoenig** [cchanxzy/react-currency-input-field#342]
**Describe the bug**
When fixedDecimalLength is 0 you can still write 2 decimals after ",".

**To Reproduce**
1. add 0 to fixedDecimalLength prop and try to write decimals

**Expected behavior**
As far as i understand you shouldn't be able to write "," or any numbers after.

**Comment by willyls-VG** [comment]
There's a similar issue with RSD. 

```tsx
const locale: 'en-US' | 'sr-RS'
<CurrencyInput 
  value={12345.67} 
  fixedDecimalLength={2}
  intlConfig={{locale: locale, currency: 'RSD'}}
/>    

// WHEN local == 'en-US'
// Expected output => RSD 12,345.67
// Actual output => RSD 1,234,567

// WHEN local == 'sr-RS'
// Expected output => 12.345,67 RSD
// Actual output => RSD 12.34567 RSD
```

This gets even more weird when you add `decimalScale={2}` to the component props.

I think this has something to do with Intl.NumberFormat asserting that RSD does not have minor units. However, everything I read says it [has two](https://simple.wikipedia.org/wiki/ISO_4217#cite_note-ReferenceA-1).

```ts
const intlFormat = new Intl.NumberFormat('sr-RS', {currency: 'RSD', style: 'currency'}).format(12345.67)
intlFormat === '12.346 RSD' // Note that is rounds up to ...46 (instead of 45)
```

I am able to get Intl.NumberFormat to return 2 decimal points if I update its config:

```ts
const intlFormat = new Intl.NumberFormat('sr-RS', {currency: 'RSD', style:'currency', minimumFractionDigits: 2}).format(12345.67)
intlFormat === '12.345,67 RSD' // Hooray!
```

Might be useful to pass in some of the props to the number formatter to enforce its rules.  Or can we just expose `Intl.NumberFormatOptions` as a prop to give us more control?
