### ISSUE TITLE
I can not remove the currency sign

### ISSUE THREAD

**Issue by ntalamdotcom** [cchanxzy/react-currency-input-field#353]
**Describe the bug**
this is my code `<CurrencyInput
                  className="entradaDinero"
                  intlConfig={{ locale: 'es-CL', currency: 'CLP' }}
                  prefix=""
                  placeholder="Please enter a number"
                  defaultValue={valueContent}
                  onValueChange={(value, name, values) => {
                    if (par.propertyToCall == undefined) {
                      return
                    }
                    if (values != undefined) {
                      const numberValue = parseFloat(values.float + "");
                      // console.log(event.target.value)
                      modifyElementByYear(element.anio, par.propertyToCall, numberValue)
                      console.log(reCalculateEverything(element))
                      modifyYearByYear(element)
                    }

                    console.log("asdf: ", value, name, values)
                  }}
                />`
However I can not remove the default $ sign

Am I missing something here?

**Expected behavior**
not seeing the currency sign

I am using NextJS

**Comment by gmartinu** [comment]
I just run into this issue minutes ago.
In my case i'm using the Mui V5 TextField and i was able to remove the currency sign changing the Intl style that is passed as the config of the IntlCurrencyInput

```
const currencyConfig: typeof IntlCurrencyInput.defaultProps.config = {
  locale: "pt-BR",
  formats: {
    number: {
      BRL: {
        style: "decimal", <- here
        currency: "BRL",
        minimumFractionDigits: 2,
        maximumFractionDigits: 2,
      },
    },
  },
};
```

This usually will be currency, but if you set to decimal still will be handle like a currency but without the prefix of it.
