### ISSUE TITLE
Currency Input Component Displays Incorrect Format

### ISSUE THREAD

**Issue by MariaBracho** [cchanxzy/react-currency-input-field#356]
**Describe the bug**
The currency input component is not formatting the value as expected when use locale "es" or "es-ES".

**Expected behavior**
The currency input should display the value in the format “76.800,00 €.”

**Actual Behavior**
The currency input currently displays the value as “76800,00 €.”

**Additional context**
I am using the following component:

const intlConfig = {
  locale: "es-ES",
  currency: "EUR",
};

`<Input
  as={CurrencyInputField}
  onValueChange={handleValueChange}
  intlConfig={intlConfig}
  value={textValue}
/>
`

**Comment by bharateq** [comment]
+1

**Comment by diego-lipinski-de-castro** [comment]
I am experiencing the same problem

**Comment by reconka** [comment]
> [Intl locale config](https://github.com/cchanxzy/react-currency-input-field#intl-locale-config) can be passed in. Please note: formatting where the currency symbol is placed after the value like a suffix eg. (1 234,56 €) might cause problems, this is still in development.

@diego-lipinski-de-castro @MariaBracho  I think the best workaround to avoid this issue is adding `groupSeparator="."` prop to CurrencyInput component.
