### ISSUE TITLE
How to allow type both "." and "," to insert decimal

### ISSUE THREAD

**Issue by piszczu4** [cchanxzy/react-currency-input-field#361]
In Poland we use "," for decimal separator. However, I want to let user type "." as well to start typical decimal numbers while still displayed as ",". Is it possible?

**Comment by DetectiveStrawberry** [comment]
I would love to have this feature present. In Italy, we also use the "," as a decimal separator, but having the component accept the "." from the keyboard would make input from the Numberpad easier.

**Comment by rimzzlabs** [comment]
1+ 

same case but different circumstances:
in cryptocurrency user can buy or sell small amount of BTC, for example: `0.0000123` BTC, this is perfectly fine on Android cause Android virtual keyboard has "." and "," key on their virtual keyboard.

However iOS virtual keyboard does not have "." period key on it, so user cannot buy or sell small amount of cryptocurrency, would love to have this feature

**Comment by rimzzlabs** [comment]
> 1+
> 
> same case but different circumstances: in cryptocurrency user can buy or sell small amount of BTC, for example: `0.0000123` BTC, this is perfectly fine on Android cause Android virtual keyboard has "." and "," key on their virtual keyboard.
> 
> However iOS virtual keyboard does not have "." period key on it, so user cannot buy or sell small amount of cryptocurrency, would love to have this feature

also my current workaround is to do this with RHF + shadcn generated form component

```tsx
<CurrencyInput
  onChange={(e) => {
   if (isIOS() && e.target.value.endsWith(",")) {
    const value = e.target.value.replace(",", ".");field.onChange(value);

                        setTimeout(() => {
                          const selectionEnd = value.length;
                          e.target.setSelectionRange(selectionEnd, selectionEnd);
                        }, 25);
                      }
                    }}

 />
```
