### ISSUE TITLE
Support for Euro notation

### ISSUE THREAD

**Issue by soulpaul** [cchanxzy/react-currency-input-field#52]
Hey! Is there a way to use the correct notation for Euro?
In Euro countries (at least for the most part of them) amounts should have commas to divide decimals from the integer part of the number and points to separate thousands (ex. € 100.000.000,00 instead of £ 100,000,000.00).
Thanks

**Comment by cchanxzy** [comment]
Hi, I did not realise that was the case for Euro! But I think it should be quite simple to implement two new props for decimal separator and thousand separators. Give me a few days, and I'll see if I get the time to do it :)

**Comment by umucorn** [comment]
That'd be great If I could choose what character to put instead of default thousand and decimal separators.

**Comment by cchanxzy** [comment]
Hi @soulpaul and @umucorn, thanks for the suggestion.

I've given it a go and implemented it, but there was a bit more changes in the code than I expected, so I've published it in a beta branch for testing.

If you would like to try it out: https://www.npmjs.com/package/react-currency-input-field/v/2.2.0-beta.1#separators

```bash
npm i react-currency-input-field@2.2.0-beta.1

yarn add react-currency-input-field@2.2.0-beta.1
```

Feel free to raise any issues you find :)

**Comment by ericblade** [comment]
Hi there!  FWIW, you might want to allow for passing in a locale, and outputting via Number.prototype.toLocaleString()

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString

Currency type is not the correct method for determining the separators, locale should be.  If I'm working in Euro, I'm still working in en-US locale, so it should read €123,456.99 .. and if someone in en-UK is working in USD, it should read $123.456,99

 Of course, allowing for custom separators is also still ok, other people might have different uses. :-)

**Comment by cchanxzy** [comment]
Thanks for the suggestion, @ericblade, it sounds like it should be pretty useful for dealing with different currencies. It's something I'll add to the list of potential improvements and todos.

For now I'm going to close this issue as I have made an attempt to implement the feature on the beta branch, if there are any other observations feel free to re-open this thread or raise a new issue :)
