### ISSUE TITLE
support for fixed decimals?

### ISSUE THREAD

**Issue by ericblade** [cchanxzy/react-currency-input-field#57]
Hi there!  I'm currently using https://www.npmjs.com/package/react-currency-input .. which is great on desktop, but is terrible on mobile.

I just saw this relatively new project here when I went to look to see if anyone has created an alternative to the above one... so I thought I'd ask for the feature that I need most: fixed decimal length inputs.  My currency inputs should always have 2 decimals, so working in USD, entering "342" should give you "$3.42" in the output display, and should return the value of the input in decimal numbers (cents)

I haven't yet looked through this source code, to see how easy it would be to modify it, or to wrap it with another component that might do that .. just thought I'd throw the idea out here, and see if you'd be interested in supporting some additional user scenarios.

**Comment by cchanxzy** [comment]
Hi @ericblade thanks for the suggestion. Initially I was going to say you could do this in the `onChange` and don't need to modify the core functionality... turns out that's not true haha.

So, since I was trying to give an example, I ended up implementing it anyway. I made a few assumptions in the functionality, so let me know if that's not what you expected.

I've put this feature on the beta branch for now: https://www.npmjs.com/package/react-currency-input-field/v/2.2.0-beta.2#fixed-decimal-length

```bash
npm i react-currency-input-field@2.2.0-beta.2

yarn add react-currency-input-field@2.2.0-beta.2
```

Note: the formatting happens `onBlur` so you'll only see the change when user navigates away.

You can also play with it on this [Code Sandbox](https://codesandbox.io/s/heuristic-silence-jq05r?file=/src/App.js).

**Comment by cchanxzy** [comment]
> It seems odd that it inserts thousands separators on the fly, but doesn't deal with the decimals until blur. So, you get like "1,234" then you blur, and it becomes "12.34".

Ah yes, that's true now that you've pointed it out. The problem with trying add the decimal on the fly is that you don't really know when the user stops typing, and the decimal point could keep on moving, which is probably more odd eg. 

123 -> 1.23
1.23*4* -> 12.34
12.34*5* -> 123.45

I haven't had to use debounce yet for this component, but that might be one of the ways to solve it. I'll have a play around  over the weekend and try to find something that works.

And regarding your other point about mobile/android, if you open another issue describing the problems you have, I can try and take a look when I get a chance. For me personally, when I've used it on mobile it's worked as I expected, but that's quite limited testing I know. Would be good to hear from you on how it can be improved.

**Comment by ericblade** [comment]
oh, it's the other component i referenced in OP that has issues on mobile/android.  That's why I went looking to see if anybody had come up with one that was more modern and worked better in the last couple of years :)  I haven't tried this one on anything yet, was just looking for alternatives to what I have now.

That one I can have it start with the value being $0.00.  When you hit a number, say if you enter 1, then it goes to $0.01  then if you enter 5, it goes to $0.15, and if you enter 9, it would become $1.59.  The trick where it all fails on mobile, is that when you are trying to delete numbers, on desktop it works fine -- backspace from $1.59 makes it $0.15, backspace again makes it $0.05, then typing another number adds that to the end, so typing 19 again would make it $5.19.  In Mobile , at least on Android, the cursor ends up in the wrong place after a backspace, so it erases one digit, but then inserts the next digit into the middle, instead of at the end.

**Comment by Automotive-369** [comment]
> oh, it's the other component i referenced in OP that has issues on mobile/android. That's why I went looking to see if anybody had come up with one that was more modern and worked better in the last couple of years :) I haven't tried this one on anything yet, was just looking for alternatives to what I have now.
> 
> That one I can have it start with the value being $0.00. When you hit a number, say if you enter 1, then it goes to $0.01 then if you enter 5, it goes to $0.15, and if you enter 9, it would become $1.59. The trick where it all fails on mobile, is that when you are trying to delete numbers, on desktop it works fine -- backspace from $1.59 makes it $0.15, backspace again makes it $0.05, then typing another number adds that to the end, so typing 19 again would make it $5.19. In Mobile , at least on Android, the cursor ends up in the wrong place after a backspace, so it erases one digit, but then inserts the next digit into the middle, instead of at the end.

have you find any solution for this ?
