### ISSUE TITLE
Ability to disable negative values

### ISSUE THREAD

**Issue by mnoster** [cchanxzy/react-currency-input-field#66]
I know recently there was a feature pushed to support negative values. 

It would be great to have a prop to `allowNegativeValue={bool}` 

This is not something we want to support by default in our application.

Thank you.

**Comment by cchanxzy** [comment]
Hi, thanks that's a good shout!

I've added the new prop `allowNegativeValue` as you suggested. This will disable the user from entering a negative value, i.e it will ignore the `-` if entered.

You can try it with the latest version `2.3.0`

Feel free to re-open this issue if that's not what you were expecting.

**Comment by mnoster** [comment]
Thank you for the quick implementation. I will be testing soon.
