### ISSUE TITLE
pre-filled value

### ISSUE THREAD

**Issue by RahulShahUI** [cchanxzy/React-Currency-Input-Field#7]
how to apply default value for this input and allow decimalLimit.

eg. $ 12,000.75

**Comment by cchanxzy** [comment]
Currently you can only add a placeholder value (as seen in examples), but not a default value.
Also, decimal values are not supported.

Those are both good suggestions though, and I will add them to a feature list. However I can't guarantee when I will have the chance to implement it.

**Comment by cchanxzy** [comment]
Thank for your suggestions.

I've added support for default value and decimalsLimit, please check out `react-currency-input-field@0.3.1` and let me know if you have any issues with the new features.
