### ISSUE TITLE
Whitespace or empty string is considered a number, thus unusable as group separator

### ISSUE THREAD

**Issue by stinodes** [cchanxzy/react-currency-input-field#76]
As the title says, currently the component throws when using either a blank string or a whitespace as group separator.  

Whitespace actually is a correct separator in certain languages, so allowing this should be a must.  
As for an empty string, this could be handy if the developer doesn't want any separator shown (I suppose `turnOffSeparators` already does this though).

**Comment by cchanxzy** [comment]
Thanks for raising this issue, you're right, it should accept a whitespace as a separator.

This should be fixed in 2.3.4, please give it a go and let me know if you find any more issues.

And thanks again for taking the time to create a fix too.
