### ISSUE TITLE
Strange cursor behaviour around prefix

### ISSUE THREAD

**Issue by luigi22** [cchanxzy/react-currency-input-field#78]
There is an issue with cursor behaviour when inserted before prefix - first entered digit is placed after prefix, next one and following ones land at the end of string.

Here's an example:

![Screen Recording 2020-10-21 at 17 00 13](https://user-images.githubusercontent.com/14167593/96742552-57f29c00-13c3-11eb-94dd-0d5f8c9d7818.gif)

I think that all entered digits should be appended to the end of string - so the value should be 1234.

I have used Example 2 from [https://cchanxzy.github.io/react-currency-input-field/](https://cchanxzy.github.io/react-currency-input-field/) and Chrome browser.

**Comment by cchanxzy** [comment]
Oh that is a bit weird! I've never noticed that.

Thanks for raising, I'll have a look into it.

**Comment by luigi22** [comment]
Thanks! I've also modified example by removing prefix and it seems that inserting characters on the beginning of the field works fine until comma separator is added:

![Screen Recording 2020-10-26 at 13 08 04](https://user-images.githubusercontent.com/14167593/97172475-5e03c680-178f-11eb-8d8d-35443e9cb5c4.gif)

**Comment by cchanxzy** [comment]
Thanks for raising this issue, this was really useful. I had never used it in that way, so I didn't know about this bug.

I've just merged a PR that should fix the cursor issue, please try using v2.3.5

Feel free to reopen if you find it's still broken.
