### ISSUE TITLE
Feature Request: Force decimal places on blur.

### ISSUE THREAD

**Issue by eabinga** [cchanxzy/react-currency-input-field#81]
Very nice control. I do have a feature request that would round it out a bit.

Example: I enter 123 (without decimal places) and I leave the input (onBlur), the field formats to 123.00
Or I enter: 123.1 and onBlur it formats to 123.10

Suggested usage: <CurrencyInput formatDecimals="2" ..... >

**Comment by cchanxzy** [comment]
Hi @eabinga, I think that's already implemented, try using the prop `precision`.

If that's not what you want, let me know :)
