### ISSUE TITLE
Example site not showing examples

### ISSUE THREAD

**Issue by JDMathew** [cchanxzy/react-currency-input-field#82]
Play with example: [Play with examples](https://cchanxzy.github.io/react-currency-input-field/)
rendering:
![Screenshot 2020-10-29 at 17 44 26](https://user-images.githubusercontent.com/17250443/97611764-82b9a180-1a0e-11eb-9581-ad3f68be232f.png)

**Comment by cchanxzy** [comment]
Thanks, it's been fixed now 👍
