### ISSUE TITLE
Defining onBlur overrides component formatting

### ISSUE THREAD

**Issue by paulraph** [cchanxzy/react-currency-input-field#83]
Hi, so I was trying that library and it seems great. The only weird thing is that, when I define my own onBlur prop, it ends up overriding the CurrencyInput one.

While looking at the code, I noticed you are merging the onChange prop with yours, but not the onBlur one. Would it be possible to have a custom onBlur prop while keeping your formatting functionailities? I need to do something with the value and blur and end up losing the formatting functionnality.

**Comment by cchanxzy** [comment]
Hi there, yeah that sounds like a good idea. 

It shouldn't be too hard to implement, I'll give it a go and get back to you.

**Comment by cchanxzy** [comment]
I've just merge a PR to add a new prop `onBlurValue` which will call the function passed in with the number only value eg. `123456` instead of `$123,456`.

I hope thats what you were requesting? If not, let me know and I can give it another go.

This should be in v2.4.0
