### ISSUE TITLE
$ as prefix causes unexpected results.

### ISSUE THREAD

**Issue by jaykaron** [cchanxzy/react-currency-input-field#84]
Using `$` as the prefix (a fairly common use case) causes unexpected behaviour.

To Reproduce:
* Change line 7 in Example 1 from `const prefix = "£";` to `const prefix = "$";`

Unexpected Behaviour 1:
* Type in `5.55` into the input
* Expected Output: **$5.55**
* Actual Output: **$.55**

Unexpected Behaviour 2:
* Type in `100` into the input
* Unfocus input (cents added as expected)
* Focus and unfocus again
* Expected Output: **$100.00**
* Actual Output: **$1.00**

I suspect the reason may be related to the regex https://github.com/cchanxzy/react-currency-input-field/blob/b206702e4d931659e7de490a9ca30223dc94eb95/src/components/utils/cleanValue.ts#L29
Where `${prefix}` must be escaped.

I plan on submitting a PR later today.

Thanks. 😄

**Comment by cchanxzy** [comment]
Hi @jaykaron, thanks for raising the issue and submitting the PR.

I was trying to replicate the issue locally, and it seems to be working as expected with "$" prefix, both onChange and onBlur. Could you share how you're implementing it?

**Comment by jaykaron** [comment]
Thanks for the fast response!
Strange. Just changing `£` to `$` in Example1.tsx on b206702 (current HEAD) gives me this behaviour.
I edited Unexpected Behaviour 1 in my original comment to change `555` to `5.55`. `555` does give the expected result.

I am running on Windows 10 and get the same behaviour in both Chrome 86 and Edge.
I even get behaviour 1 on example 2 of the live demo at https://cchanxzy.github.io/react-currency-input-field/

![react-currency-input-field](https://user-images.githubusercontent.com/22824315/98041880-a30fa480-1df0-11eb-981c-77cf0a474de3.gif)

**Comment by cchanxzy** [comment]
Ah yes, I see what you mean now. You're right that is a bug related to the regex not being escaped properly. 

I implemented a fix, which is very similar to your PR, except there's an existing function to escape regex in the codebase, so I thought it would be better to use that instead.

Thanks again for raising the bug! Should be fixed now in v2.3.6

**Comment by jaykaron** [comment]
Great. Thanks for the speedy fix!
