### ISSUE TITLE
abbreviation values

### ISSUE THREAD

**Issue by simonpkerr** [cchanxzy/react-currency-input-field#92]
Hi, first thanks for the great package, very useful. I just noticed though that you can input any of the abbreviations as the first character, without a value. is this a known issue? It'd also be nice to be able to disable abbreviations like you can with separators etc.

![Screenshot 2020-11-18 at 13 32 41](https://user-images.githubusercontent.com/995892/99536681-966b7e80-29a2-11eb-9a01-cc30f95efa58.png)

**Comment by cchanxzy** [comment]
Hi, yes that's a bug so thanks for raising this issue and bringing it to my attention!

I've merged a PR to fix the bug, and also included the option disable abbreviations by passing in `turnOffAbbreviations` to the component. 

These changes should be in v2.7.0, so feel free to check it out. Hope that helps :)
